name: Integration Tests
on: [push]
jobs:
  uiTest:
    name: Run Android Tests
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - uses: malinskiy/action-android/install-sdk@release/0.0.3
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.3
        with:
          cmd: ./gradlew connectedAndroidTest --stacktrace
          api: 21
          tag: default
          abi: x86
